version: '3.8'

services:
  write_db:
    image: postgres:latest
    container_name: write_db
    restart: always
    environment:
      POSTGRES_DB: write_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - write_db_data:/var/lib/postgresql/data
      - ./scripts_db/writeScript.sql:/docker-entrypoint-initdb.d/writeScript.sql

  read_db:
    image: postgres:latest
    container_name: read_db
    restart: always
    environment:
      POSTGRES_DB: read_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5441:5432"
    volumes:
      - read_db_data:/var/lib/postgresql/data
      - ./scripts_db/readScript.sql:/docker-entrypoint-initdb.d/readScript.sql

volumes:
  write_db_data:
  read_db_data:
